### PR TITLE
missing starting quote in relay section

### PR DESCRIPTION
**Pull request by DefectivenessYT**
This caused an install issue for me - i narrowed it down to the missing starting quotation mark here.

image

image

### CODE REVIEW

**Comment by DefectivenessYT** [comment]
With the added quotation mark, the install proceeds perfectly :)
image

**Comment by DefectivenessYT** [comment]
Also - How would i go about uncapping / changing the listener cap on the azurarelay icecast servers?

**Comment by HexDevv** [comment]
GOOD JOB DEFECTIVENESSYT

**Comment by DefectivenessYT** [comment]
POG

**Pull request merged**
